In [7]:
import numpy as np
arr=np.array([1,2,3,4,5,6])
slice=arr[1:4]
slice

array([2, 3, 4])

In [5]:
arr[4]=99
arr

array([ 1,  2,  3,  4, 99,  6])

In [6]:
arr=np.array([1,2,3],dtype='float64')

In [12]:
arr1=np.array(([1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]))
arr1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [14]:
arr1[2,1]

12

In [15]:
arr1[0,0:2]

array([1, 2])

In [24]:
arr1[0:2,0:4]

array([[1, 2, 3, 4],
       [6, 7, 8, 9]])

In [20]:
arr1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [34]:
arr=np.array([[[1,2,3],[11,12,13]],[[4,5,6],[14,15,16]],[[7,8,9],[17,18,19]]])     #3D ARRAY
arr

array([[[ 1,  2,  3],
        [11, 12, 13]],

       [[ 4,  5,  6],
        [14, 15, 16]],

       [[ 7,  8,  9],
        [17, 18, 19]]])

In [35]:
arr[2,1,2]

19

In [49]:
print(arr[0:3,1:2,0:2])
print(arr[0:,1,0:2])

[[[11 12]]

 [[14 15]]

 [[17 18]]]
[[11 12]
 [14 15]
 [17 18]]


In [50]:
arr

array([[[ 1,  2,  3],
        [11, 12, 13]],

       [[ 4,  5,  6],
        [14, 15, 16]],

       [[ 7,  8,  9],
        [17, 18, 19]]])

In [51]:
arr[2,1,2]

19

In [57]:
arr2=np.array([1,2,3,4,5,6,7,8,9])
arr1=arr2.copy()

In [58]:
arr1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [59]:
arr1[3]=99
arr2

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [60]:
arr1

array([ 1,  2,  3, 99,  5,  6,  7,  8,  9])

In [61]:
arr2[1]=100
print(arr2)
print(arr1)

[  1 100   3   4   5   6   7   8   9]
[ 1  2  3 99  5  6  7  8  9]


In [63]:
original_arr=np.array([1,2,3])
view_arr=original_arr[1:]
copy_arr=np.copy(original_arr)
print(view_arr)
print(copy_arr)
print(original_arr)

[2 3]
[1 2 3]
[1 2 3]


In [64]:
arr=np.array([1,2,3,4,5,6])
arr_view=arr.view()
arr_copy=arr.copy()
print(arr_view)
print(arr_copy)

[1 2 3 4 5 6]
[1 2 3 4 5 6]


In [90]:
arr[0]=100
print(arr_view)
print(arr_copy)
arr
print(arr_view.base)
print(arr_copy.base)

[100   2   3   4   5   6]
[1 2 3 4 5 6]
[100   2   3   4   5   6]
None


In [80]:
arr=np.array([1,2,3],dtype='int')
print(arr)
arr=np.array([1,2,3],dtype='float32')
print(arr)
arr=np.array([1,2,3],dtype='str')
print(arr)

[1 2 3]
[1. 2. 3.]
['1' '2' '3']


In [82]:
print(arr_view.base)

[100   2   3   4   5   6]


In [83]:
arr

array(['1', '2', '3'], dtype='<U1')