In [1]:
import numpy as np
arr=np.array([1,2,3])
print(arr)

[1 2 3]


In [2]:
type(arr)  #TYPE OF ARRAY

numpy.ndarray

In [3]:
zeros_arr=np.zeros((2,3))   
zeros_arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [4]:
ones_arr=np.ones((2,3))
np.ones

<function numpy.ones(shape, dtype=None, order='C', *, like=None)>

In [5]:
ones_arr=np.ones((3,2))
ones_arr

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [6]:
arrange_arr=np.arrange(0,10,2)
arange_arr

AttributeError: module 'numpy' has no attribute 'arrange'

In [7]:
arrange_arr

NameError: name 'arrange_arr' is not defined

In [8]:
arange_arr=np.arange(0,10,2)
arange_arr

array([0, 2, 4, 6, 8])

In [9]:
#arange_arr=np.arange(0,10,2)
linespace_arr=np.linespace(0,1,5)
linespace_arr

AttributeError: module 'numpy' has no attribute 'linespace'

In [10]:
linspace_arr=np.linespace(0,1,5)
linspace_arr

AttributeError: module 'numpy' has no attribute 'linespace'

In [11]:
linspace_arr=np.linspace(0,1,5)
linspace_arr

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [12]:
linspace_arr=np.linspace(0,5,5)
linspace_arr

array([0.  , 1.25, 2.5 , 3.75, 5.  ])

In [13]:
linspace_arr=np.linspace(0,5,10)
linspace_arr

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [14]:
linspace_arr=np.linspace(0,1,3)
linspace_arr

array([0. , 0.5, 1. ])

In [15]:
linspace_arr=np.linspace(0,2,1)
linspace_arr

array([0.])

In [16]:
linspace_arr=np.linspace(0,2,2)
linspace_arr

array([0., 2.])

In [17]:
linspace_arr=np.linspace(1,2,2)
linspace_arr

array([1., 2.])

In [39]:
random_arr=np.random.rand(2,3)
random_arr

array([[0.01112621, 0.41212717, 0.03040856],
       [0.93853484, 0.99250594, 0.91284085]])

In [29]:
random_arr=np.random.rand(1,2)
random_arr

array([[0.20227356, 0.16142221]])

In [20]:
random_arr=np.random.randint(1,2)
random_arr

1

In [21]:
random_arr=np.random.randint(3,2)
random_arr

ValueError: low >= high

In [22]:
random_arr=np.random.randint(2,4)
random_arr

2

In [25]:
random_arr=np.random.randint(2,4)
random_arr

3

In [43]:
random_arr=np.random.randint(1,20,size=(5,6))
print(random_arr)

[[ 2  9 16 17 14 13]
 [13 10  2  8  6  9]
 [15 13  7  6  6 17]
 [16 17 14  6 17  2]
 [18  8  4  9  4  3]]


In [44]:
arr=np.array([1,2,3,4,5])
arr[2]

3

In [54]:
arr1=np.random.rand(3,3)*9
print(arr1)

[[3.51953829 7.30450216 5.33533427]
 [6.22918074 4.14634271 7.97287265]
 [8.99587255 1.94011907 0.17827012]]


In [55]:
random_arr=np.random.randint(2,4)
random_arr

array([[4.51953829, 8.30450216, 6.33533427],
       [7.22918074, 5.14634271, 8.97287265],
       [9.99587255, 2.94011907, 1.17827012]])

In [58]:
random_arr=np.random.randint(low=2,size=(1,3))
random_arr

array([[0, 0, 1]])

In [59]:
arr2=np.random.randint(2,5)*6

In [60]:
arr2

24

In [79]:
arr2=np.random.rand(3,4)*9+1   #TO GET RANDOM FLOATING NUMBER ABOVE 1 
arr2

array([[2.2950986 , 5.79558274, 3.86508359, 5.1700021 ],
       [8.26338643, 4.43788254, 4.22720521, 6.39341217],
       [7.46921017, 7.99354275, 6.6866261 , 2.13866523]])

In [83]:
arr3=np.random.randint(low=1,high=3,size=(3,3))
arr3

array([[2, 2, 1],
       [1, 1, 1],
       [1, 1, 2]])

In [88]:
arr=np.array([1,2,3,4,5])
print(arr[3])
arr[1]=10
print(arr)

4
[ 1 10  3  4  5]


In [91]:
multi_arr=np.array([[1,2,3],[4,5,6],[1,4,5]])
print(multi_arr)

[[1 2 3]
 [4 5 6]
 [1 4 5]]


In [102]:
arr=np.array([1,2,3,4,5,6,7,8,9,10])
newarr=arr.reshape(5,2)
newarr

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [105]:
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr=arr.reshape(2,3,2)
newarr

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])